version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
    environment:
      - PORT=4200
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - simulation

  simulation:
    build:
      context: ./project_ws
      dockerfile: Dockerfile.simulation
    environment:
      - DISPLAY=${DISPLAY}
    ports:
      - "9090:9090"
      - "11345:11345"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./project_ws:/app
    privileged: true  
    network_mode: "host"
