version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
    environment:
      - PORT=4200
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app