version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
    environment:
      - PORT=4200

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - simulation

  simulation:
    build:
      context: ./project_ws
      dockerfile: Dockerfile.simulation
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./project_ws:/app
    privileged: true  
    network_mode: "host"
